server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://192.168.11.188:3306/tuhui?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 3EJExYbsG#*QHpqjHm
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
